name: NodeJS with Webpack

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          token: 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

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          yarn install
          yarn build

      - name: switch from HTTP to SSH
        run: git remote set-url origin https://nathanziarczyk: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@github.com/ziarczyknathan/bobs-flowers
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: add github author - email
        run: git config user.email "nathan.ziar@gmail.com"
      - name: add github author - name
        run: git config user.name "Github Actions"
      - name: commit changed files
        run: git commit -m "Auto adding build files to the repo"
      - name: fetch from master
        run: git fetch origin main
      - name: push code to master
        run: git push origin HEAD:main
